spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity"
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /identity

jwt:
  signerKey: "mCTW1Ojv+FHt7grOk5vBdCxWjdBQkALjB8A6VKm2qw5kRizIMcFkErSFKc5II3sL"
  valid-duration: 20 # in second
  refreshable-duration: 36000 # in seconds